export enum ActionTypes {
    FIND_USER = 'FIND_USER',
    FIND_USER_SUCCESS = 'FIND_USER_SUCCESS',
    FIND_USER_ERROR = 'FIND_USER_ERROR',
    FETCH_USERS = 'FETCH_USERS',
    FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS',
    FETCH_USERS_ERROR = 'FETCH_USERS_ERROR',
}